Added search readme
Enterprise-CMCS/cmcs-eregulations pull request #1104
Opened 2023-12-12 18:23 UTC by thwalker6

Resolves #

**Description-**

**This pull request changes...**

- expected change 1

**Steps to manually verify this change...**

1. steps to view and verify change

2023-12-13 17:17 UTC, peggles2 requested changes

2023-12-13 19:44 UTC, cgodwin1 commented on README.md
>  ```
I think the naming convention is referring to "ApplicationName_Model" from before.

2023-12-14 14:42 UTC, thwalker6 commented on README.md
>  ```
Caleb is correct.  If you look at the tables in sql that is the naming convention of the tables.  Its all lowercase letters for the file names.

2023-12-14 22:16 UTC, peggles2 reviewed
LGTM

2023-12-15 12:23 UTC, thwalker6 commented
> LGTM

You didnt actually approve it :D

2023-12-15 17:47 UTC, cgodwin1 approved these changes

2023-12-15 20:27 UTC, peggles2 approved these changes

2023-12-15 20:28 UTC, merged