EREGCSC-1890 Make the statute data available in the Django backend
Enterprise-CMCS/cmcs-eregulations pull request #837
Opened 2023-05-31 20:27 UTC by cgodwin1

Resolves #1890

**Description-**

To support the new statute table design, data including section name and associated title must be parsed and stored. To do this we parse the XML DOM and extract the info from the table of contents.

**This pull request changes...**

- Conversion importer first parses the table of contents
    - Some XML have a single title, others have multiple. This is supported thanks to the `containsShortTitle` tag and the structure of the TOC.
- If converter's section is in the TOC, we use that data to construct the new object
- If it is not, we create the object anyway with a blank name and title, and inform the user

**Steps to manually verify this change...**

1. Run unit tests (these tests use golden files for SSA and ACA due to the different parsing methods)
2. Go to the admin panel and try to import each of the following:
    a. https://www.govinfo.gov/content/pkg/COMPS-8766/uslm/COMPS-8766.xml
    b. https://www.govinfo.gov/content/pkg/COMPS-9307/uslm/COMPS-9307.xml
    c. https://www.govinfo.gov/content/pkg/COMPS-8765/uslm/COMPS-8765.xml
    d. https://www.govinfo.gov/content/pkg/COMPS-8768/uslm/COMPS-8768.xml
    e. https://www.govinfo.gov/content/pkg/COMPS-8763/uslm/COMPS-8763.xml
3. You should see no errors and all converters are imported, even if some fail to have a name/title.

2023-06-01 14:14 UTC, cgodwin1 commented on solution/backend/regulations/admin.py
> +            dom = minidom.parseString(text)
This user provided value is SME only. Uncontrolled entity expansion would cause slowness for this user only.

2023-06-01 14:14 UTC, cgodwin1 commented on solution/backend/regulations/templates/admin/conversions_imported.html
> +                <li><a target="_blank" href="{% url 'admin:regulations_statutelinkconverter_change' c.id %}">Title {{ c.statute_title }} section {{ c.section }} of the {{ c.act }} → {{ c.title }} USC
These are not external links, they were going to the admin panel.

2023-06-01 14:14 UTC, cgodwin1 commented on solution/backend/regulations/templates/admin/conversions_imported.html
> +                <li><a target="_blank" href="{% url 'admin:regulations_statutelinkconverter_change' f.id %}">{{ f.act }} section {{ f.section }} → {{ f.title }} USC {{ f.usc }}</a></li>
Not external, admin panel only.

2023-06-05 19:26 UTC, peggles2 requested changes
lgtm just one minor change.

2023-06-05 19:26 UTC, peggles2 requested changes
lgtm just one minor change.

2023-06-08 15:51 UTC, cgodwin1 commented on solution/backend/regulations/admin.py
> +SECTION_APPEND_PATTERN = rf"({DASH_PATTERN}+[a-z0-9]+)."
Resolved in [8d9071d](https://github.com/Enterprise-CMCS/cmcs-eregulations/pull/837/commits/8d9071de78a46e23a815272a8157b2e8a146093b)

2023-06-12 19:00 UTC, peggles2 approved these changes

2023-06-15 16:32 UTC, merged