EREGCSC-1909 getting by page results in our search
Enterprise-CMCS/cmcs-eregulations pull request #853
Opened 2023-06-13 16:01 UTC by thwalker6

Resolves # EREGCSC-1909

**Description-**

Urls that had a page number were not appearing properly in the search results

- Search results from search.gov with a page number will now appear in the results.

2023-06-14 16:49 UTC, peggles2 requested changes
Looks good, just need to fix the typos.

2023-06-14 16:49 UTC, peggles2 commented on solution/backend/resources/views/resources.py
> +        # gets thes first of the list to sbeing the query set
small typo sbeing change to being.

2023-06-14 16:49 UTC, peggles2 commented on solution/backend/resources/views/resources.py
> +        # now we are comibning the remaing ones by putting an or statement in between.
just some typos to fix comibning

2023-06-15 17:37 UTC, thwalker6 commented on solution/backend/resources/tests/test_viewset_functions.py
>              self.assertEqual(f'...site{num} snippet', r.snippet)
Added a test that does both.

2023-06-15 17:37 UTC, thwalker6 commented on solution/backend/resources/views/resources.py
> +        # now we are comibning the remaing ones by putting an or statement in between.
fixed

2023-06-15 17:37 UTC, thwalker6 commented on solution/backend/resources/views/resources.py
> +        # gets thes first of the list to sbeing the query set
fixed

2023-06-15 18:11 UTC, peggles2 approved these changes
LGTM 🌮

2023-06-16 13:39 UTC, merged