Implementsnyk
Enterprise-CMCS/cmcs-eregulations pull request #957
Opened 2023-09-11 18:52 UTC by KaushikSamtek

Resolves #

**Description- This PR is for Snyk implementation. It contains the workflow to run the scan and then calls the service that creates the Jira tickets**

**This pull request changes none of the existing files. Only one new workflow file was added.**

- expected change 1

**Steps to manually verify this change**

1. when a pull request is made to main, there will be a Snyk run in the actions tab.

2023-09-11 18:55 UTC, KaushikSamtek commented
Sorry, I just had to remove push from the title for snyk. No major changes were made.

2023-09-13 13:29 UTC, thwalker6 commented on .github/workflows/snyk-test.yml
> +        uses: actions/checkout@v2
We currently use checkout@v3 on our application since that is the latest version.  Please update.

2023-09-13 13:30 UTC, thwalker6 requested changes
Please update the github actions for checkout to v3.

2023-09-13 17:33 UTC, KaushikSamtek commented
I have updated the version to v3. I also saw this branch was a commit behind main so I updated that also and not it is ready to go. Let me know if there is anything else

2023-09-13 18:26 UTC, thwalker6 approved these changes
lgtm

2023-09-19 14:08 UTC, merged