EREGCSC-2217 - Buckets use SSL
Enterprise-CMCS/cmcs-eregulations pull request #967
Opened 2023-09-19 19:15 UTC by thwalker6

Resolves #

**Description-**

**This pull request changes...**

- expected change 1

**Steps to manually verify this change...**

1. steps to view and verify change

2023-09-26 18:46 UTC, peggles2 approved these changes

2023-09-26 18:54 UTC, peggles2 requested changes
This is good to have but it does not fix the issue

SecurityHub Finding - S3.8 S3 Block Public Access setting should be enabled at the bucket-level

Adding this block to the bucket should solve it for you (but this is what could accidentally block CloudFront if it was connecting publicly)
PublicAccessBlockConfiguration:
  BlockPublicAcls: true
  BlockPublicPolicy: true
  IgnorePublicAcls: true
  RestrictPublicBuckets: true
  docs here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-publicaccessblockconfiguration.html

2023-09-27 11:23 UTC, thwalker6 commented
> This is good to have but it does not fix the issue
> 
> SecurityHub Finding - S3.8 S3 Block Public Access setting should be enabled at the bucket-level
> 
> Adding this block to the bucket should solve it for you (but this is what could accidentally block CloudFront if it was connecting publicly) PublicAccessBlockConfiguration: BlockPublicAcls: true BlockPublicPolicy: true IgnorePublicAcls: true RestrictPublicBuckets: true docs here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-publicaccessblockconfiguration.html

This is not that ticket.  This has  nothing to do with it

2023-09-27 13:55 UTC, peggles2 approved these changes

2023-09-27 14:04 UTC, merged